version: '3'
services:
  openbas-dev-pgsql:
    container_name: openbas-dev-pgsql
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    ports:
      - "5432:5432"
    restart: unless-stopped
  openbas-test-pgsql:
    container_name: openbas-test-pgsql
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    ports:
      - "5433:5432"
    restart: unless-stopped
  openbas-dev-minio:
    container_name: openbas-dev-minio
    image: minio/minio:latest
    ports:
      - "10000:9000"
      - "10001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
  openbas-dev-rabbitmq:
    container_name: openbas-dev-rabbitmq
    image: rabbitmq:4.0-management
    restart: unless-stopped
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
  openbas-dev-caldera:
    container_name: openbas-dev-caldera
    image: openbas/caldera-server:5.1.0
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://localhost:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml
#  openbas-pyroscope:
#    container_name: openbas-pyroscope
#    image: grafana/pyroscope:latest
#    restart: unless-stopped
#    ports:
#      - "4040:4040"
#  openbas-telemetry-otlp:
#    container_name: openbas-telemetry-otlp
#    image: otel/opentelemetry-collector-contrib:0.119.0
#    restart: unless-stopped
#    volumes:
#      - "./otlp-config.yaml:/etc/config/otlp-config.yaml"
#      - "./telemetry.json:/telemetry.json"
#    command:
#      - '--config=/etc/config/otlp-config.yaml'
#    ports:
#      - "1010:1010"
  openbas-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
