#!/usr/bin/env python3
"""Generate Claude Code path-scoped rules from the Copilot instruction files.

.github/instructions/*.instructions.md stays the source of truth. Claude Code
ignores their `applyTo` frontmatter, so each one is copied to .claude/rules/
with a `paths` frontmatter mirroring `applyTo`. Claude Code then loads it when
it reads a matching file. The body is copied rather than `@`-imported because
Claude Code does not expand imports inside path-scoped rules.

Run after adding an instruction file or changing an `applyTo`:

    python .github/scripts/sync-claude-rules.py

With --check, exits 1 instead of writing when a wrapper is missing or stale.
"""

import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
INSTRUCTIONS = REPO / ".github" / "instructions"
RULES = REPO / ".claude" / "rules"
SUFFIX = ".instructions.md"


def split(path: Path) -> tuple[str, str]:
    _, frontmatter, body = path.read_text().split("---", 2)
    return frontmatter, body.lstrip("\n")


def apply_to(path: Path) -> list[str]:
    frontmatter, _ = split(path)
    match = re.search(r"^applyTo:\s*(\|\s*\n((?:[ \t]+.*\n?)+)|\"(.*)\")", frontmatter, re.M)
    if not match:
        sys.exit(f"{path.relative_to(REPO)}: no applyTo in frontmatter")
    raw = match.group(2) if match.group(2) is not None else match.group(3)
    return [glob.strip() for glob in raw.split(",") if glob.strip()]


def relink(body: str) -> str:
    """Point relative Markdown links, written from .github/instructions/, at the same files from .claude/rules/."""

    def rewrite(match: re.Match) -> str:
        target, anchor = match.group(1), match.group(2) or ""
        if re.match(r"^[a-z]+:", target) or target.startswith("/"):
            return match.group(0)
        return f"]({os.path.relpath(INSTRUCTIONS / target, RULES)}{anchor})"

    return re.sub(r"\]\(([^)#\s]+)(#[^)\s]*)?\)", rewrite, body)


def render(source: Path) -> str:
    paths = "\n".join(f'  - "{glob}"' for glob in apply_to(source))
    return (
        f"---\npaths:\n{paths}\n---\n\n"
        f"<!-- Generated by .github/scripts/sync-claude-rules.py from "
        f"{source.relative_to(REPO)}. Do not edit: change the source and re-run the script. -->\n\n"
        f"{relink(split(source)[1])}"
    )


def main() -> int:
    check = "--check" in sys.argv[1:]
    expected = {
        RULES / (source.name.removesuffix(SUFFIX) + ".md"): render(source)
        for source in sorted(INSTRUCTIONS.glob(f"*{SUFFIX}"))
    }
    stale = [rule for rule, content in expected.items() if not rule.exists() or rule.read_text() != content]
    orphans = [rule for rule in RULES.glob("*.md") if rule not in expected and "sync-claude-rules.py" in rule.read_text()]

    if check:
        for rule in stale + orphans:
            print(f"out of date: {rule.relative_to(REPO)}")
        if stale or orphans:
            print("run: python .github/scripts/sync-claude-rules.py")
        return 1 if stale or orphans else 0

    RULES.mkdir(parents=True, exist_ok=True)
    for rule in stale:
        rule.write_text(expected[rule])
        print(f"wrote {rule.relative_to(REPO)}")
    for rule in orphans:
        rule.unlink()
        print(f"removed {rule.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
