coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 0
        informational: true
    patch:
      default:
        target: 50%
        threshold: 0
        informational: true
comment:
  behavior: default
  require_changes: false
  require_base: false
  after_n_builds: 1
  comment: |
    Coverage for this PR: **${coverage.prc}%**
    Expected project target: **50%**