coverage:
  status:
    project:
      default:
        target: 80%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

      openaev-api:
        target: 80%
        threshold: 30%
        informational: true

      openaev-front:
        target: 80%
        informational: true
