import { Chip, type ChipSeverity, Tooltip, TooltipContent, TooltipTrigger } from '@filigran/design-system';
import { CheckIndeterminateIcon, EditIcon, LogoXtmOneIcon } from 'filigran-icon';

import { useFormatter } from '../../../../components/i18n';
import { type DetectionRemediation } from '../../../../utils/api-types';

export interface Props { author_rule: DetectionRemediation['author_rule'] }

const DetectionRemediationInfo = ({ author_rule }: Props) => {
  const { t } = useFormatter();

  let label = '';
  let severity: ChipSeverity = 'neutral';
  let icon;

  if (author_rule === 'AI_OUTDATED') {
    label = t('Payload changed since rule was edited');
    severity = 'medium';
    icon = <CheckIndeterminateIcon fontSize="small" />;
  } else if (author_rule === 'AI') {
    label = t('Rules generated by AI');
    severity = 'info';
    icon = <LogoXtmOneIcon fontSize="small" />;
  } else if (author_rule === 'HUMAN') {
    label = t('Rules written by Human');
    severity = 'info';
    icon = <EditIcon fontSize="small" />;
  }

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Chip startIcon={icon} label={label} severity={severity} />
      </TooltipTrigger>
      {label && <TooltipContent>{label}</TooltipContent>}
    </Tooltip>
  );
};
export default DetectionRemediationInfo;
