enum ContractOutputElementType {
  account_with_password_not_required = 'AccountWithPasswordNotRequired',
  admin_username = 'AdminUsername',
  asreproastable_account = 'AsreproastableAccount',
  computer = 'Computer',
  credentials = 'Credentials',
  cve = 'CVE',
  delegation = 'Delegation',
  group = 'Group',
  ipv4 = 'IPv4',
  ipv6 = 'IPv6',
  kerberoastable_account = 'KerberoastableAccount',
  number = 'Number',
  password_policy = 'PasswordPolicy',
  port = 'Port',
  portscan = 'PortsScan',
  share = 'Share',
  sid = 'Sid',
  text = 'Text',
  username = 'Username',
  vulnerability = 'Vulnerability',
}

export const CONTRACT_OUTPUT_ELEMENT_TYPE_KEYS = [
  'account_with_password_not_required',
  'admin_username',
  'asreproastable_account',
  'computer',
  'credentials',
  'cve',
  'delegation',
  'group',
  'ipv4',
  'ipv6',
  'kerberoastable_account',
  'number',
  'password_policy',
  'port',
  'portscan',
  'share',
  'sid',
  'text',
  'username',
  'vulnerability',
] as const;

export default ContractOutputElementType;
