import { Tooltip, useTheme } from "@mui/material";
import { CheckIndeterminateIcon, EditIcon, LogoXtmOneIcon } from "filigran-icon";
import { useFormatter } from "../../../../components/i18n";

export interface Props {
  content: string,
  authorRules: string,
  payloadUpdatedAt: string,
  detectionRemediationUpdateAt: string

}

const DetectionRemediationInfo = ({
                                    content,
                                    authorRules,
                                    payloadUpdatedAt,
                                    detectionRemediationUpdateAt
                                  }: Props) => {

  const theme = useTheme();
  const {t} = useFormatter();
  return (
    <div>
      {content != '' &&
        authorRules == 'AI' &&
          <span style={{padding: 10}}>
             <Tooltip title={t("Rules generated by AI")}>
                  <LogoXtmOneIcon style={{width: 20, height: 20, color: theme.palette.ai.main}}/>
             </Tooltip>
          </span>
      }
      {content != '' && authorRules == 'HUMAN' &&
          <span style={{padding: 10}}>
            <Tooltip title={t("Rules write by Human")}>
              <EditIcon style={{width: 15, height: 15, color: theme.palette.primary.main}}/>
            </Tooltip>
          </span>
      }

      {
        content != '' && payloadUpdatedAt &&
        (new Date(payloadUpdatedAt).getTime() >
          new Date(detectionRemediationUpdateAt).getTime()
        )
        && <span style={{padding: 10}}>
              <Tooltip title={<div style={{
                whiteSpace: 'pre-line',
                textAlign: 'center'
              }}>{t("AI remediation may be outdated: payload updated after remediation")}</div>}>
                  <CheckIndeterminateIcon style={{width: 20, height: 20, color: theme?.palette?.grey.A100}}
                                          color={theme?.palette?.grey.A100}/>
              </Tooltip>
          </span>
      }
    </div>
  )
}
export default DetectionRemediationInfo;