name: "Release"

on:
  workflow_call:
    inputs:
      branch_platform:
        type: string
        default: 'master'
        required: true
      previous_version:
        type: string
        default: ''
        required: true
      new_version:
        type: string
        default: ''
        required: true
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openbas
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          repository: OpenBAS-Platform/openbas
          ref: ${{ inputs.branch_platform }}
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
      - name: execute py script # run file
        run: |
          python scripts/release.py ${{ inputs.branch_platform }} ${{ inputs.previous_version }} ${{ inputs.new_version }} ${{ secrets.RELEASE_TOKEN }}